#!/usr/bin/bash
#
#SBATCH --job-name=iqtree10k
#SBATCH --cpus-per-task=8
#SBATCH --mem=20g
#SBATCH --mail-type=ALL
#SBATCH --output=iqtree-%j.out
#SBATCH --error=iqtree-%j.err
#SBATCH --partition=medium
#SBATCH --time=12:00:00
 
###usage###
#run as sbatch .sh <alignment_file.fasta>
#Use the alignment generated by GTDB-TK workflow. It can be found in this location (gtdb_output/align/gtdbtk.bac120.user_msa.fasta.gz) after using the 04 - GTDBTK classification script.

module purge
module load anaconda3
source $ANACONDA3_ROOT/etc/profile.d/conda.sh 

conda activate /scratch/projects/eei/software/iqtree

ALIGNMENT=$1

iqtree -s ${ALIGNMENT} -m TEST -alrt 10000 -bb 10000 -nt 8
